# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RtMunsellRgb
                                 A QGIS plugin
 This plugin converts Munsell color system code into RBG value.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-14
        copyright            : (C) 2022 by Matjaž Mori
        email                : matjaz.mori@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Matjaž Mori'
__date__ = '2022-04-14'
__copyright__ = '(C) 2022 by Matjaž Mori'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RtMunsellRgb class from file RtMunsellRgb.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rt_munsell import RtMunsellRgbPlugin
    return RtMunsellRgbPlugin()
